"""Adiciona campos lot e expires_at ao modelo Medication

Revision ID: 506dcf657f91
Revises: 
Create Date: 2025-08-28 22:58:42.477740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506dcf657f91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('lot')

    # ### end Alembic commands ###
